In [1]:
#https://www.youtube.com/watch?v=aG9LG_B5bSs

import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv('train.csv')
conn = sqlite3.connect('phone.db')

c = conn.cursor()
c.execute('CREATE TABLE IF NOT EXISTS phonedata ({})'.format(','.join(df.columns)))

In [13]:
for row in df.iterrows():
    sql = 'INSERT INTO phonedata({}) VALUES ({})'.format(','.join(df.columns), ','.join(['?']*len(df.columns)))
    c.execute(sql, tuple(row[1]))
conn.commit()

In [4]:
df.shape

(2000, 21)

In [14]:
c.execute('DELETE FROM phonedata WHERE RAM <1000')
conn.commit()

In [17]:
df1 = pd.read_sql_query('SELECT * from phonedata', conn)
df1

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842.0,0.0,2.2,0.0,1.0,0.0,7.0,0.6,188.0,2.0,...,20.0,756.0,2549.0,9.0,7.0,19.0,0.0,0.0,1.0,1.0
1,1021.0,1.0,0.5,1.0,0.0,1.0,53.0,0.7,136.0,3.0,...,905.0,1988.0,2631.0,17.0,3.0,7.0,1.0,1.0,0.0,2.0
2,563.0,1.0,0.5,1.0,2.0,1.0,41.0,0.9,145.0,5.0,...,1263.0,1716.0,2603.0,11.0,2.0,9.0,1.0,1.0,0.0,2.0
3,615.0,1.0,2.5,0.0,0.0,0.0,10.0,0.8,131.0,6.0,...,1216.0,1786.0,2769.0,16.0,8.0,11.0,1.0,0.0,0.0,2.0
4,1821.0,1.0,1.2,0.0,13.0,1.0,44.0,0.6,141.0,2.0,...,1208.0,1212.0,1411.0,8.0,2.0,15.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1597,1467.0,1.0,0.5,0.0,0.0,0.0,18.0,0.6,122.0,5.0,...,888.0,1099.0,3962.0,15.0,11.0,5.0,1.0,1.0,1.0,3.0
1598,858.0,0.0,2.2,0.0,1.0,0.0,50.0,0.1,84.0,1.0,...,528.0,1416.0,3978.0,17.0,16.0,3.0,1.0,1.0,0.0,3.0
1599,1965.0,1.0,2.6,1.0,0.0,0.0,39.0,0.2,187.0,4.0,...,915.0,1965.0,2032.0,11.0,10.0,16.0,1.0,1.0,1.0,2.0
1600,1911.0,0.0,0.9,1.0,1.0,1.0,36.0,0.7,108.0,8.0,...,868.0,1632.0,3057.0,9.0,1.0,5.0,1.0,1.0,0.0,3.0
1601,510.0,1.0,2.0,1.0,5.0,1.0,45.0,0.9,168.0,6.0,...,483.0,754.0,3919.0,19.0,4.0,2.0,1.0,1.0,1.0,3.0

In [18]:
conn.close()